# Generated by Django 6.0.7 on 2026-08-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_reasoning', models.TextField(help_text='Why the agent made this decision')),
                ('proposed_action', models.TextField(help_text='What the agent suggests doing')),
                ('human_decision', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited')], help_text='What the human decided', max_length=50, null=True)),
                ('sources_used', models.TextField(blank=True, help_text='KB articles or sources the agent cited', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Decision Log',
                'verbose_name_plural': 'Decision Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
