# Generated by Django 6.0.7 on 2026-08-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_decisionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionlog',
            name='sources_used',
            field=models.JSONField(blank=True, default=list, help_text='KB articles or sources the agent cited'),
        ),
    ]
