# Generated by Django 6.0.7 on 2026-08-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_decisionlog_sources_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionlog',
            name='decided_at',
            field=models.DateTimeField(blank=True, help_text='When the human made a decision on this item', null=True),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='edited_action',
            field=models.TextField(blank=True, help_text='Human-edited version of the proposed action, if edited', null=True),
        ),
    ]
