# Generated by Django 6.0.7 on 2026-08-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(db_index=True, help_text='Source file the chunk came from.', max_length=255)),
                ('page', models.PositiveIntegerField(help_text='1-based page number in the source document.')),
                ('section', models.CharField(blank=True, default='', help_text='Nearest heading above the chunk, if one was detected.', max_length=255)),
                ('chunk_index', models.PositiveIntegerField(help_text='Position of the chunk within its document.')),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(help_text='Estimated tokens in the chunk (~4 chars per token).')),
                ('category', models.CharField(blank=True, choices=[('technical', 'Technical'), ('billing', 'Billing'), ('account', 'Account'), ('general', 'General')], db_index=True, help_text='Optional category filter, matching ticket categories.', max_length=50, null=True)),
                ('embedding', models.JSONField(help_text='Normalised embedding vector.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['document_name', 'chunk_index'],
                'unique_together': {('document_name', 'chunk_index')},
            },
        ),
    ]
