# Generated by Django 6.0.7 on 2026-08-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='kb_documents/')),
                ('category', models.CharField(blank=True, choices=[('technical', 'Technical'), ('billing', 'Billing'), ('account', 'Account'), ('general', 'General')], help_text='Optional category filter for retrieval.', max_length=50, null=True)),
                ('chunk_count', models.PositiveIntegerField(default=0, editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Knowledge Document',
                'verbose_name_plural': 'Knowledge Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
