# Generated by Django 6.0.7 on 2026-08-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_knowledgedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionlog',
            name='triage_error',
            field=models.TextField(blank=True, default='', help_text='Why the agent run failed, if it did. Empty and no proposed_action means triage is still running; empty with a proposed_action means the row is ready for a human.'),
        ),
    ]
