# Generated by Django 6.0.7 on 2026-08-28 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_decisionlog_triage_error'),
        ('token_blacklist', '0013_alter_blacklistedtoken_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('outstanding_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='token_blacklist.outstandingtoken')),
            ],
        ),
    ]
